# -*- coding: utf-8 -*-
"""regression,py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UzAIWGz7PTu2dUfeIJI0lIxrdarQRxK0
"""

import numpy as np
import pandas as pd

from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('/content/Salary_Data.csv')

X = data[['YearsExperience']]
y = data['Salary']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model = DecisionTreeRegressor(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

msc =mean_squared_error(y_test,y_pred)

r2 =r2_score(y_test,y_pred)

print(f"Mean Squared Error: {msc}")
print(f"R_Squared:{r2}")

plt.figure(figsize=(8,6))
plt.scatter(X_test,y_test,color='blue',label='Actual')
plt.plot(X_test,y_pred,color='red',label='predicted')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.title('Decision Tree Regression')
plt.legend()
plt.show()